// Description: This file contains class definition for the quest related data model.

const { QuestExpRewardCoefficient } = require('./static.js');

function generateUniqueID(prefix) {
	// generate a unique ID that start with the prefix and followed by a random text of 6 characters with numbers and letters
	return prefix + Math.random().toString(36).substring(2, 8);
}

/**
 * RawQuest is the class that contains the raw data of the quest submitted by the user.
 * `RawQuest` is used to store the raw data of the quest before it is reviewed by the admin.
 */
class RawQuest {
	/**
	 * Create a RawQuest.
	 */
	constructor() {
		this.rawQuestId = null;
		this.description = null;
		this.createBy = null;
		this.durationTextRaw = null;
		this.reviewed = false;
		this.approved = false;

		// this should be generated by the database when the data is inserted
		this.createAt = null;
	}

	/**
	 * Set the description of the quest.
	 * @param {string} description - The description of the quest.
	 */
	setDescription(description) {
		this.description = description;
	}

	/**
	 * Set the creator of the quest.
	 * @param {string} dcId - The ID of the creator.
	 */
	setCreateBy(dcId) {
		this.createBy = dcId;
	}

	/**
	 * Set the raw duration text of the quest.
	 * @param {string} durationTextRaw - The raw duration text of the quest.
	 */
	setDuration(durationTextRaw) {
		this.durationTextRaw = durationTextRaw;
	}

	/**
	 * Generates a unique quest raw ID and assigns it to the `RawQuestId` property.
	 * @returns {void}
	 */
	generateRawQuestId() {
		this.rawQuestId = generateUniqueID('QID-');
	}

	/**
	 * Set the `reviewed` property.
	 * @returns {void}
	 */
	setReviewed(status) {
		this.reviewed = status;
	}

	/**
	 * Set the `approved` property.
	 * @returns {void}
	 */
	setApproved(status) {
		this.approved = status;
	}

	/**
	 * Update the attributes of the RawQuest from a store.
	 * @param {Object} attributes - The attributes to update.
	 */
	updateAttributeFromStore(attributes) {
		this.rawQuestId = attributes['rawQuestId'];
		this.description = attributes['description'];
		this.createBy = attributes['createBy'];
		this.durationTextRaw = attributes['durationTextRaw'];
		this.reviewed = attributes['reviewed'];
		this.createAt = attributes['createAt'];
		this.approved = attributes['approved'];
	}

	/**
	 * Return the attributes of the RawQuest to be stored.
	 * @returns {Object} - The attributes of the RawQuest.
	 */
	returnAttributeToStore() {
		return {
			'rawQuestId': this.rawQuestId,
			'description': this.description,
			'createBy': this.createBy,
			'durationTextRaw': this.durationTextRaw,
			'reviewed': this.reviewed,
			'approved': this.approved,
		};
	}
}


/**
 * `Quest` is the class that represents a quest data model.
 * Each `Quest` is created by the admin after review a `RawQuest` object.
 */
class Quest {
	/**
	 * Create a Quest.
	 */
	constructor() {
		this.questId = null;
		this.description = null;
		this.questType = null;
		this.repeatable = false;
		this.rewardCoefficient = QuestExpRewardCoefficient.REWARD_NORMAL;
		this.rewardExp = null;
		this.createAt = null;
		this.expireAt = null;
		this.createBy = null;
		this.reviewedBy = null;
		this.durationTextRaw = null;
	}

	/**
	 * Set the duration text of the quest.
	 * @param {string} durationTextRaw - The duration text of the quest.
	 */
	setDurationTextRaw(durationTextRaw) {
		this.durationTextRaw = durationTextRaw;
	}

	/**
	 * Set the description of the quest.
	 * @param {string} description - The description of the quest.
	 */
	setDescription(description) {
		this.description = description;
	}

	/**
	 * Set the quest type of the quest.
	 * @param {string} questType - The quest type of the quest.
	 */
	setQuestType(questType) {
		this.questType = questType;
	}

	/**
	 * Set the repeatable flag of the quest.
	 * @param {boolean} repeatable - The repeatable flag of the quest.
	 */
	setRepeatable(repeatable) {
		this.repeatable = repeatable;
	}

	/**
	 * Set the reward coefficient of the quest.
	 * @param {number} rewardCoefficient - The reward coefficient of the quest.
	 */
	setRewardCoefficient(rewardCoefficient) {
		this.rewardCoefficient = rewardCoefficient;
	}

	/**
	 * Set the reward experience of the quest.
	 * @param {number} rewardExp - The reward experience of the quest.
	 */
	setRewardExp(rewardExp) {
		this.rewardExp = rewardExp;
	}

	/**
	 * Set the creation time of the quest.
	 * @param {Date} createAt - The creation time of the quest.
	 */
	setCreateAt(createAt) {
		this.createAt = createAt;
	}

	/**
	 * Set the expiration time of the quest.
	 * @param {Date} expireAt - The expiration time of the quest.
	 */
	setExpireAt(expireAt) {
		this.expireAt = expireAt;
	}

	/**
	 * Set the creator ID of the quest.
	 * @param {string} createBy - The creator ID of the quest.
	 */
	setCreateBy(createBy) {
		this.createBy = createBy;
	}

	/**
	 * Set the reviewer ID of the quest.
	 * @param {string} reviewedBy - The reviewer ID of the quest.
	 */
	setReviewedBy(reviewedBy) {
		this.reviewedBy = reviewedBy;
	}

	/**
	 * Update the attributes of the Quest from a store.
	 * @param {Object} attributes - The attributes to update.
	 */
	updateAttributeFromStore(attributes) {
		this.questId = attributes['questId'];
		this.description = attributes['description'];
		this.questType = attributes['questType'];
		this.durationTextRaw = attributes['durationTextRaw'];
		this.repeatable = attributes['repeatable'];
		this.rewardCoefficient = attributes['rewardCoefficient'];
		this.rewardExp = attributes['rewardExp'];
		this.createAt = attributes['createAt'];
		this.expireAt = attributes['expireAt'];
		this.createBy = attributes['createBy'];
		this.reviewedBy = attributes['reviewedBy'];
	}

	/**
	 * Return the attributes of the Quest to be stored.
	 * @returns {Object} - The attributes of the Quest.
	 */
	returnAttributeToStore() {
		return {
			'questId': this.questId,
			'description': this.description,
			'questType': this.questType,
			'durationTextRaw': this.durationTextRaw,
			'repeatable': this.repeatable,
			'rewardCoefficient': this.rewardCoefficient,
			'rewardExp': this.rewardExp,
			'expireAt': this.expireAt,
			'createBy': this.createBy,
			'reviewedBy': this.reviewedBy,
		};
	}
}


/**
 * QuestInstance is the class that contains the instance of data related to a quest accepted by the user.
 * Each Quest object can be accepted by multiple users, and each user will have their own corresponding QuestInstance object.
 */
class QuestInstance {
	/**
	 * Create a QuestInstance.
	 * @param {string} questId - The ID of the quest.
	 * @param {string} dcId - The ID of the user.
	 */
	constructor(questId, dcId) {
		this.questId = questId;
		this.dcId = dcId;
		this.accepted_at = null;
		this.completed_at = null;
		this.failed_at = null;
	}

	/**
	 * Update the attributes of the QuestInstance from a store.
	 * @param {Object} attributes - The attributes to update.
	 */
	updateAttributeFromStore(attributes) {
		this.questId = attributes['questId'];
		this.dcId = attributes['dcId'];
		this.accepted_at = attributes['accepted_at'];
		this.completed_at = attributes['completed_at'];
		this.failed_at = attributes['failed_at'];
	}

	/**
	 * Return the attributes of the QuestInstance to be stored.
	 * @returns {Object} - The attributes of the QuestInstance.
	 */
	returnAttributeToStore() {
		return {
			'questId': this.questId,
			'dcId': this.dcId,
			'accepted_at': this.accepted_at,
			'completed_at': this.completed_at,
			'failed_at': this.failed_at,
		};
	}

	/**
	 * Get the current time.
	 * @returns {Date} - The current time.
	 */
	getCurrentTime() {
		return new Date();
	}

	/**
	 * Set the accepted_at attribute to the current time.
	 */
	questAcceptAt() {
		this.accepted_at = this.getCurrentTime();
	}

	/**
	 * Set the completed_at attribute to the current time.
	 */
	questCompleteAt() {
		this.completed_at = this.getCurrentTime();
	}

	/**
	 * Set the failed_at attribute to the current time.
	 */
	questFailedAt() {
		this.failed_at = this.getCurrentTime();
	}
}


module.exports = {
	Quest,
	RawQuest,
	QuestInstance,
};